import Link from 'next/link';

export default function Home() {
  return (
    <main>
      {/* Navigation */}
      <nav className="container" style={{ padding: '2rem 1rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ fontWeight: 700, fontSize: '1.25rem' }}>HIVON.</div>
        <div style={{ display: 'flex', gap: '2rem', alignItems: 'center' }}>
          <Link href="/blog" className="label-mono">Blog</Link>
          <Link href="/login" className="button button-primary">Login</Link>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="hero-gradient section" style={{ minHeight: '80vh', display: 'flex', alignItems: 'center' }}>
        <div className="container">
          <div className="label-mono" style={{ marginBottom: '1rem', color: 'rgba(255,255,255,0.8)' }}>AI-Powered Blogging</div>
          <h1>Write. Summary. Elevate.</h1>
          <p style={{ maxWidth: '600px', fontSize: '1.25rem', marginTop: '1.5rem', color: 'rgba(255,255,255,0.9)' }}>
            The next generation of content sharing. Automatically generate high-quality summaries with Google AI and manage your community with robust role-based controls.
          </p>
          <div style={{ marginTop: '3rem', display: 'flex', gap: '1rem' }}>
            <Link href="/blog" className="button" style={{ background: '#ffffff', color: '#000000' }}>Explore Feed</Link>
            <Link href="/login" className="button button-outline" style={{ borderColor: '#ffffff', color: '#ffffff' }}>Get Started</Link>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="section bg-white">
        <div className="container">
          <div style={{ textAlign: 'center', marginBottom: '4rem' }}>
            <div className="label-mono">Platform Features</div>
            <h2 style={{ fontSize: '2.5rem' }}>Powering the Future of Content</h2>
          </div>
          
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '2rem' }}>
            <div style={{ padding: '2rem', background: 'var(--glass-dark)', borderRadius: '8px' }}>
              <h3 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>AI Summarization</h3>
              <p>Every post automatically receives a 200-word summary generated by Google's latest AI models, stored and served for maximum reader retention.</p>
            </div>
            <div style={{ padding: '2rem', background: 'var(--glass-dark)', borderRadius: '8px' }}>
              <h3 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>Role-Based Access</h3>
              <p>Built-in tiers for Authors, Viewers, and Admins ensures secure content creation and powerful moderation tools.</p>
            </div>
            <div style={{ padding: '2rem', background: 'var(--glass-dark)', borderRadius: '8px' }}>
              <h3 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>Figma Aesthetics</h3>
              <p>A strictly calibrated monochrome interface that lets your content shine, inspired by the world's leading design tools.</p>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
